### ISSUE TITLE
Broken Library Plugin on 1494 to 1497 (OBS: My Java Version are up to date).

### ISSUE THREAD

**Issue by batatabraz** [freenet/plugin-Library#22]
The plugin Library could not be loaded: class java.lang.IllegalArgumentException: IV must be no more than 127 bits
       at freenet.crypt.OCBBlockCipher_v149.init(OCBBlockCipher_v149.java:177)
       at freenet.crypt.AEADInputStream.<init>(AEADInputStream.java:42)
       at freenet.crypt.AEADInputStream.createAES(AEADInputStream.java:195)
       at freenet.crypt.AEADCryptBucket.getInputStreamUnbuffered(AEADCryptBucket.java:68)
       at freenet.crypt.AEADCryptBucket.getInputStream(AEADCryptBucket.java:62)
       at freenet.support.io.PaddedBucket.getInputStream(PaddedBucket.java:149)
       at freenet.pluginmanager.PluginStores.loadPluginStore(PluginStores.java:116)
       at freenet.pluginmanager.PluginStores.loadPluginStore(PluginStores.java:96)
       at freenet.pluginmanager.PluginRespirator.getStore(PluginRespirator.java:248)
       at plugins.Library.Library.<init>(Library.java:130)
       at plugins.Library.Library.init(Library.java:88)
       at plugins.Library.Main.runPlugin(Main.java:143)
       at freenet.pluginmanager.PluginHandler.startPlugin(PluginHandler.java:44)
       at freenet.pluginmanager.PluginManager.realStartPlugin(PluginManager.java:381)
       at freenet.pluginmanager.PluginManager.startPluginOfficial(PluginManager.java:351)
       at freenet.pluginmanager.PluginManager.startPluginOfficial(PluginManager.java:343)
       at freenet.clients.http.PproxyToadlet$2.run(PproxyToadlet.java:142)
       at freenet.support.PooledExecutor$MyThread.innerRun(PooledExecutor.java:259)
       at freenet.support.PooledExecutor$MyThread.realRun(PooledExecutor.java:197)
       at freenet.support.io.NativeThread.run(NativeThread.java:156)

**Comment by slrslr** [comment]
Why Library plugin is enabled by default to confuse users by returning message on a search page:
"Task failed : Failed to fetch content"
and a log file  "ERROR): Bogus timeout" exception.

Some more details about the issue [here](https://paste.nolog.cz/?29032c61e658fad5#2xNKwsJPkxRNqLnfJKGA9SaboszjEwrTwWe4TSJRinJJ).

Developers, please consider disabling the plugin until/if it is working again.
